server:
    port: 9080
spring:
    datasource:
        password: user123
        url: jdbc:mysql://localhost:3306/driversugestion
        username: user
    jpa:
        database : MYSQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql : true
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
    
    kafka:
        topic: driver_location
        listener:
            missing-topics-fatal: false
        consumer:
            bootstrap-servers: localhost:9092
            group-id: group_id
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer